# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- task: Npm@1
  displayName: 'Install SASS'
  inputs:
    command: 'custom'
    customCommand: 'install -g sass'

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: '**/*.sln'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: '**/*.sln'
    arguments: '-c Release -v minimal --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test [Core]'
  inputs:
    command: 'test'
    projects: '**/SimpleBlazorGrid.Core.Tests.Unit.csproj'
    testRunTitle: 'Core'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test [Entity Framework]'
  inputs:
    command: 'test'
    projects: '**/SimpleBlazorGrid.EntityFramework.Tests.csproj'
    testRunTitle: 'Entity Framework'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack [Core]'
  inputs:
    command: 'pack'
    packagesToPack: '**/SimpleBlazorGrid.Core.csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'PACKAGE_VERSION_CORE'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack [Entity Framework]'
  inputs:
    command: 'pack'
    packagesToPack: '**/SimpleBlazorGrid.EntityFramework.csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'PACKAGE_VERSION_EF'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Core'
  inputs:
    PathtoPublish: '**\SimpleBlazorGrid.Core.$(PACKAGE_VERSION_CORE).nupkg'
    ArtifactName: 'Core'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Entity Framework'
  inputs:
    PathtoPublish: '**\SimpleBlazorGrid.EntityFramework.$(PACKAGE_VERSION_EF).nupkg'
    ArtifactName: 'Entity Framework'
    publishLocation: 'Container'

