trigger:
- none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- task: Npm@1
  displayName: 'Install SASS'
  inputs:
    command: 'custom'
    customCommand: 'install -g sass'

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: '**/SimpleBlazorGrid.Website.csproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: '**/SimpleBlazorGrid.Website.csproj'
    arguments: '-c Release -v minimal --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/SimpleBlazorGrid.Website.csproj'
    arguments: '-c Release --no-build'
    modifyOutputPath: false